---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agentry.io
  resources:
  - agentclasses
  - modelproviders
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentry.io
  resources:
  - agentclasses/finalizers
  - modelproviders/finalizers
  verbs:
  - update
- apiGroups:
  - agentry.io
  resources:
  - agentclasses/status
  - modelproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agentry.io
  resources:
  - agents
  - agenttasks
  verbs:
  - get
  - list
  - watch
