## Append samples of your project ##
resources:
- kaalm_v1alpha1_agentclass.yaml
- kaalm_v1alpha1_modelprovider.yaml
- kaalm_v1alpha1_agent.yaml
- kaalm_v1alpha1_agenttask.yaml
- kaalm_v1alpha1_agentchannel.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
