//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannel) DeepCopyInto(out *AgentChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannel.
func (in *AgentChannel) DeepCopy() *AgentChannel {
	if in == nil {
		return nil
	}
	out := new(AgentChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelList) DeepCopyInto(out *AgentChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelList.
func (in *AgentChannelList) DeepCopy() *AgentChannelList {
	if in == nil {
		return nil
	}
	out := new(AgentChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelSession) DeepCopyInto(out *AgentChannelSession) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelSession.
func (in *AgentChannelSession) DeepCopy() *AgentChannelSession {
	if in == nil {
		return nil
	}
	out := new(AgentChannelSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelSpec) DeepCopyInto(out *AgentChannelSpec) {
	*out = *in
	out.AgentRef = in.AgentRef
	in.Webhook.DeepCopyInto(&out.Webhook)
	out.Session = in.Session
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelSpec.
func (in *AgentChannelSpec) DeepCopy() *AgentChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AgentChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelStatus) DeepCopyInto(out *AgentChannelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelStatus.
func (in *AgentChannelStatus) DeepCopy() *AgentChannelStatus {
	if in == nil {
		return nil
	}
	out := new(AgentChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelWebhook) DeepCopyInto(out *AgentChannelWebhook) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	in.UserID.DeepCopyInto(&out.UserID)
	in.Content.DeepCopyInto(&out.Content)
	if in.CallbackURL != nil {
		in, out := &in.CallbackURL, &out.CallbackURL
		*out = new(string)
		**out = **in
	}
	if in.CallbackAuth != nil {
		in, out := &in.CallbackAuth, &out.CallbackAuth
		*out = new(ChannelAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelWebhook.
func (in *AgentChannelWebhook) DeepCopy() *AgentChannelWebhook {
	if in == nil {
		return nil
	}
	out := new(AgentChannelWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClass) DeepCopyInto(out *AgentClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClass.
func (in *AgentClass) DeepCopy() *AgentClass {
	if in == nil {
		return nil
	}
	out := new(AgentClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassEgress) DeepCopyInto(out *AgentClassEgress) {
	*out = *in
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHosts != nil {
		in, out := &in.AllowedHosts, &out.AllowedHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassEgress.
func (in *AgentClassEgress) DeepCopy() *AgentClassEgress {
	if in == nil {
		return nil
	}
	out := new(AgentClassEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassImage) DeepCopyInto(out *AgentClassImage) {
	*out = *in
	if in.AllowedImages != nil {
		in, out := &in.AllowedImages, &out.AllowedImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassImage.
func (in *AgentClassImage) DeepCopy() *AgentClassImage {
	if in == nil {
		return nil
	}
	out := new(AgentClassImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassLifecycle) DeepCopyInto(out *AgentClassLifecycle) {
	*out = *in
	out.DefaultIdleTimeout = in.DefaultIdleTimeout
	out.MaxIdleTimeout = in.MaxIdleTimeout
	out.DefaultHibernationDelay = in.DefaultHibernationDelay
	out.MaxHibernationDelay = in.MaxHibernationDelay
	out.DefaultWakeTimeout = in.DefaultWakeTimeout
	out.MaxWakeTimeout = in.MaxWakeTimeout
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassLifecycle.
func (in *AgentClassLifecycle) DeepCopy() *AgentClassLifecycle {
	if in == nil {
		return nil
	}
	out := new(AgentClassLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassList) DeepCopyInto(out *AgentClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassList.
func (in *AgentClassList) DeepCopy() *AgentClassList {
	if in == nil {
		return nil
	}
	out := new(AgentClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassNetwork) DeepCopyInto(out *AgentClassNetwork) {
	*out = *in
	in.Egress.DeepCopyInto(&out.Egress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassNetwork.
func (in *AgentClassNetwork) DeepCopy() *AgentClassNetwork {
	if in == nil {
		return nil
	}
	out := new(AgentClassNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassPersistence) DeepCopyInto(out *AgentClassPersistence) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassPersistence.
func (in *AgentClassPersistence) DeepCopy() *AgentClassPersistence {
	if in == nil {
		return nil
	}
	out := new(AgentClassPersistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassPodMetadata) DeepCopyInto(out *AgentClassPodMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassPodMetadata.
func (in *AgentClassPodMetadata) DeepCopy() *AgentClassPodMetadata {
	if in == nil {
		return nil
	}
	out := new(AgentClassPodMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassResources) DeepCopyInto(out *AgentClassResources) {
	*out = *in
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.MaxLimits != nil {
		in, out := &in.MaxLimits, &out.MaxLimits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassResources.
func (in *AgentClassResources) DeepCopy() *AgentClassResources {
	if in == nil {
		return nil
	}
	out := new(AgentClassResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassRuntime) DeepCopyInto(out *AgentClassRuntime) {
	*out = *in
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassRuntime.
func (in *AgentClassRuntime) DeepCopy() *AgentClassRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentClassRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassSecurity) DeepCopyInto(out *AgentClassSecurity) {
	*out = *in
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassSecurity.
func (in *AgentClassSecurity) DeepCopy() *AgentClassSecurity {
	if in == nil {
		return nil
	}
	out := new(AgentClassSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassSpec) DeepCopyInto(out *AgentClassSpec) {
	*out = *in
	in.Runtime.DeepCopyInto(&out.Runtime)
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Persistence.DeepCopyInto(&out.Persistence)
	if in.AllowedProviders != nil {
		in, out := &in.AllowedProviders, &out.AllowedProviders
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Network.DeepCopyInto(&out.Network)
	in.Security.DeepCopyInto(&out.Security)
	in.Lifecycle.DeepCopyInto(&out.Lifecycle)
	in.PodMetadata.DeepCopyInto(&out.PodMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassSpec.
func (in *AgentClassSpec) DeepCopy() *AgentClassSpec {
	if in == nil {
		return nil
	}
	out := new(AgentClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentClassStatus) DeepCopyInto(out *AgentClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentClassStatus.
func (in *AgentClassStatus) DeepCopy() *AgentClassStatus {
	if in == nil {
		return nil
	}
	out := new(AgentClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLifecycle) DeepCopyInto(out *AgentLifecycle) {
	*out = *in
	out.IdleTimeout = in.IdleTimeout
	out.HibernationDelay = in.HibernationDelay
	out.WakeTimeout = in.WakeTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLifecycle.
func (in *AgentLifecycle) DeepCopy() *AgentLifecycle {
	if in == nil {
		return nil
	}
	out := new(AgentLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMCPServer) DeepCopyInto(out *AgentMCPServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMCPServer.
func (in *AgentMCPServer) DeepCopy() *AgentMCPServer {
	if in == nil {
		return nil
	}
	out := new(AgentMCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPersistence) DeepCopyInto(out *AgentPersistence) {
	*out = *in
	if in.SizeGi != nil {
		in, out := &in.SizeGi, &out.SizeGi
		*out = new(int32)
		**out = **in
	}
	if in.ExistingClaim != nil {
		in, out := &in.ExistingClaim, &out.ExistingClaim
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPersistence.
func (in *AgentPersistence) DeepCopy() *AgentPersistence {
	if in == nil {
		return nil
	}
	out := new(AgentPersistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProviderReference) DeepCopyInto(out *AgentProviderReference) {
	*out = *in
	out.ProviderRef = in.ProviderRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProviderReference.
func (in *AgentProviderReference) DeepCopy() *AgentProviderReference {
	if in == nil {
		return nil
	}
	out := new(AgentProviderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentService) DeepCopyInto(out *AgentService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentService.
func (in *AgentService) DeepCopy() *AgentService {
	if in == nil {
		return nil
	}
	out := new(AgentService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	out.AgentClassRef = in.AgentClassRef
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]AgentProviderReference, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Persistence.DeepCopyInto(&out.Persistence)
	out.Lifecycle = in.Lifecycle
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(AgentService)
		**out = **in
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]AgentMCPServer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastActivityTime != nil {
		in, out := &in.LastActivityTime, &out.LastActivityTime
		*out = (*in).DeepCopy()
	}
	if in.PhaseTransitionTime != nil {
		in, out := &in.PhaseTransitionTime, &out.PhaseTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.HibernatedAt != nil {
		in, out := &in.HibernatedAt, &out.HibernatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTask) DeepCopyInto(out *AgentTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTask.
func (in *AgentTask) DeepCopy() *AgentTask {
	if in == nil {
		return nil
	}
	out := new(AgentTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskArtifact) DeepCopyInto(out *AgentTaskArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskArtifact.
func (in *AgentTaskArtifact) DeepCopy() *AgentTaskArtifact {
	if in == nil {
		return nil
	}
	out := new(AgentTaskArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskCompletion) DeepCopyInto(out *AgentTaskCompletion) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskCompletion.
func (in *AgentTaskCompletion) DeepCopy() *AgentTaskCompletion {
	if in == nil {
		return nil
	}
	out := new(AgentTaskCompletion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskList) DeepCopyInto(out *AgentTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskList.
func (in *AgentTaskList) DeepCopy() *AgentTaskList {
	if in == nil {
		return nil
	}
	out := new(AgentTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskPersistence) DeepCopyInto(out *AgentTaskPersistence) {
	*out = *in
	if in.SizeGi != nil {
		in, out := &in.SizeGi, &out.SizeGi
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskPersistence.
func (in *AgentTaskPersistence) DeepCopy() *AgentTaskPersistence {
	if in == nil {
		return nil
	}
	out := new(AgentTaskPersistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskSpec) DeepCopyInto(out *AgentTaskSpec) {
	*out = *in
	out.AgentClassRef = in.AgentClassRef
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]AgentProviderReference, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Persistence.DeepCopyInto(&out.Persistence)
	out.Completion = in.Completion
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]AgentTaskArtifact, len(*in))
		copy(*out, *in)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskSpec.
func (in *AgentTaskSpec) DeepCopy() *AgentTaskSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskStatus) DeepCopyInto(out *AgentTaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ArtifactValues != nil {
		in, out := &in.ArtifactValues, &out.ArtifactValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskStatus.
func (in *AgentTaskStatus) DeepCopy() *AgentTaskStatus {
	if in == nil {
		return nil
	}
	out := new(AgentTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelAuth) DeepCopyInto(out *ChannelAuth) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.HMAC != nil {
		in, out := &in.HMAC, &out.HMAC
		*out = new(ChannelHMAC)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelAuth.
func (in *ChannelAuth) DeepCopy() *ChannelAuth {
	if in == nil {
		return nil
	}
	out := new(ChannelAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelExtractor) DeepCopyInto(out *ChannelExtractor) {
	*out = *in
	if in.FromHeader != nil {
		in, out := &in.FromHeader, &out.FromHeader
		*out = new(string)
		**out = **in
	}
	if in.FromBody != nil {
		in, out := &in.FromBody, &out.FromBody
		*out = new(string)
		**out = **in
	}
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelExtractor.
func (in *ChannelExtractor) DeepCopy() *ChannelExtractor {
	if in == nil {
		return nil
	}
	out := new(ChannelExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelHMAC) DeepCopyInto(out *ChannelHMAC) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.SignaturePrefix != nil {
		in, out := &in.SignaturePrefix, &out.SignaturePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelHMAC.
func (in *ChannelHMAC) DeepCopy() *ChannelHMAC {
	if in == nil {
		return nil
	}
	out := new(ChannelHMAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProvider) DeepCopyInto(out *ModelProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProvider.
func (in *ModelProvider) DeepCopy() *ModelProvider {
	if in == nil {
		return nil
	}
	out := new(ModelProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderBudget) DeepCopyInto(out *ModelProviderBudget) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]ModelProviderBudgetPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterUSD != nil {
		in, out := &in.ClusterUSD, &out.ClusterUSD
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderBudget.
func (in *ModelProviderBudget) DeepCopy() *ModelProviderBudget {
	if in == nil {
		return nil
	}
	out := new(ModelProviderBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderBudgetPolicy) DeepCopyInto(out *ModelProviderBudgetPolicy) {
	*out = *in
	if in.DegradeTo != nil {
		in, out := &in.DegradeTo, &out.DegradeTo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderBudgetPolicy.
func (in *ModelProviderBudgetPolicy) DeepCopy() *ModelProviderBudgetPolicy {
	if in == nil {
		return nil
	}
	out := new(ModelProviderBudgetPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderBudgetUsage) DeepCopyInto(out *ModelProviderBudgetUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderBudgetUsage.
func (in *ModelProviderBudgetUsage) DeepCopy() *ModelProviderBudgetUsage {
	if in == nil {
		return nil
	}
	out := new(ModelProviderBudgetUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderHealthCheck) DeepCopyInto(out *ModelProviderHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderHealthCheck.
func (in *ModelProviderHealthCheck) DeepCopy() *ModelProviderHealthCheck {
	if in == nil {
		return nil
	}
	out := new(ModelProviderHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderList) DeepCopyInto(out *ModelProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderList.
func (in *ModelProviderList) DeepCopy() *ModelProviderList {
	if in == nil {
		return nil
	}
	out := new(ModelProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderModel) DeepCopyInto(out *ModelProviderModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderModel.
func (in *ModelProviderModel) DeepCopy() *ModelProviderModel {
	if in == nil {
		return nil
	}
	out := new(ModelProviderModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderRateLimits) DeepCopyInto(out *ModelProviderRateLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderRateLimits.
func (in *ModelProviderRateLimits) DeepCopy() *ModelProviderRateLimits {
	if in == nil {
		return nil
	}
	out := new(ModelProviderRateLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderSpec) DeepCopyInto(out *ModelProviderSpec) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelProviderModel, len(*in))
		copy(*out, *in)
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Budget.DeepCopyInto(&out.Budget)
	out.RateLimits = in.RateLimits
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	out.HealthCheck = in.HealthCheck
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderSpec.
func (in *ModelProviderSpec) DeepCopy() *ModelProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ModelProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelProviderStatus) DeepCopyInto(out *ModelProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BudgetUsage != nil {
		in, out := &in.BudgetUsage, &out.BudgetUsage
		*out = make([]ModelProviderBudgetUsage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelProviderStatus.
func (in *ModelProviderStatus) DeepCopy() *ModelProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ModelProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}
